In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("Hotel_Reservations.csv")
df

,Booking_ID,no_of_adults,no_of_children,no_of_weekend_nights,no_of_week_nights,type_of_meal_plan,required_car_parking_space,room_type_reserved,lead_time,arrival_year,arrival_month,arrival_date,market_segment_type,repeated_guest,no_of_previous_cancellations,no_of_previous_bookings_not_canceled,avg_price_per_room,no_of_special_requests,booking_status
0,INN00001,2,0,1,2,Meal Plan 1,0,Room_Type 1,224,2017,10,2,Offline,0,0,0,65.00,0,Not_Canceled
1,INN00002,2,0,2,3,Not Selected,0,Room_Type 1,5,2018,11,6,Online,0,0,0,106.68,1,Not_Canceled
2,INN00003,1,0,2,1,Meal Plan 1,0,Room_Type 1,1,2018,2,28,Online,0,0,0,60.00,0,Canceled
3,INN00004,2,0,0,2,Meal Plan 1,0,Room_Type 1,211,2018,5,20,Online,0,0,0,100.00,0,Canceled
4,INN00005,2,0,1,1,Not Selected,0,Room_Type 1,48,2018,4,11,Online,0,0,0,94.50,0,Canceled
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36270,INN36271,3,0,2,6,Meal Plan 1,0,Room_Type 4,85,2018,8,3,Online,0,0,0,167.80,1,Not_Canceled
36271,INN36272,2,0,1,3,Meal Plan 1,0,Room_Type 1,228,2018,10,17,Online,0,0,0,90.95,2,Canceled
36272,INN36273,2,0,2,6,Meal Plan 1,0,Room_Type 1,148,2018,7,1,Online,0,0,0,98.39,2,Not_Canceled
36273,INN36274,2,0,0,3,Not Selected,0,Room_Type 1,63,2018,4,21,Online,0,0,0,94.50,0,Canceled
36274,INN36275,2,0,1,2,Meal Plan 1,0,Room_Type 1,207,2018,12,30,Offline,0,0,0,161.67,0,Not_Canceled

# DescripciÃ³n del Dataset

A continuaciÃ³n se describe cada columna del dataset:

- **Booking_ID**: Identificador Ãºnico de cada reserva.
- **no_of_adults**: NÃºmero de adultos.
- **no_of_children**: NÃºmero de niÃ±os.
- **no_of_weekend_nights**: NÃºmero de noches de fin de semana (sÃ¡bado o domingo) que el huÃ©sped se quedÃ³ o reservÃ³ en el hotel.
- **no_of_week_nights**: NÃºmero de noches de semana (de lunes a viernes) que el huÃ©sped se quedÃ³ o reservÃ³ en el hotel.
- **type_of_meal_plan**: Tipo de plan de comidas reservado por el cliente.
- **required_car_parking_space**: Â¿Requiere el cliente un espacio de estacionamiento? (0 - No, 1 - SÃ­).
- **room_type_reserved**: Tipo de habitaciÃ³n reservada por el cliente. Los valores estÃ¡n cifrados (codificados) por INN Hotels.
- **lead_time**: NÃºmero de dÃ­as entre la fecha de reserva y la fecha de llegada.
- **arrival_year**: AÃ±o de la fecha de llegada.
- **arrival_month**: Mes de la fecha de llegada.
- **arrival_date**: DÃ­a del mes de la fecha de llegada.
- **market_segment_type**: DesignaciÃ³n del segmento de mercado.
- **repeated_guest**: Â¿Es el cliente un huÃ©sped repetido? (0 - No, 1 - SÃ­).
- **no_of_previous_cancellations**: NÃºmero de reservas anteriores que fueron canceladas por el cliente antes de la reserva actual.
- **no_of_previous_bookings_not_canceled**: NÃºmero de reservas anteriores no canceladas por el cliente antes de la reserva actual.
- **avg_price_per_room**: Precio promedio por dÃ­a de la reserva; los precios de las habitaciones son dinÃ¡micos. (en euros).
- **no_of_special_requests**: NÃºmero total de solicitudes especiales realizadas por el cliente (por ejemplo, piso alto, vista desde la habitaciÃ³n, etc.).
- **booking_status**: Indicador que muestra si la reserva fue cancelada o no.

In [3]:
df.columns

Index(['Booking_ID', 'no_of_adults', 'no_of_children', 'no_of_weekend_nights',
       'no_of_week_nights', 'type_of_meal_plan', 'required_car_parking_space',
       'room_type_reserved', 'lead_time', 'arrival_year', 'arrival_month',
       'arrival_date', 'market_segment_type', 'repeated_guest',
       'no_of_previous_cancellations', 'no_of_previous_bookings_not_canceled',
       'avg_price_per_room', 'no_of_special_requests', 'booking_status'],
      dtype='object')

In [4]:
nombres_espanol = {
    'Booking_ID': 'ID_Reserva',
    'no_of_adults': 'Num_Adultos',
    'no_of_children': 'Num_Ninos',
    'no_of_weekend_nights': 'Noches_FinSemana',
    'no_of_week_nights': 'Noches_Semana',
    'type_of_meal_plan': 'Tipo_Plan_Comidas',
    'required_car_parking_space': 'Estacionamiento_Requerido',
    'room_type_reserved': 'Tipo_Habitacion',
    'lead_time': 'Dias_Antelacion',
    'arrival_year': 'AÃ±o_Llegada',
    'arrival_month': 'Mes_Llegada',
    'arrival_date': 'Dia_Llegada',
    'market_segment_type': 'Tipo_Segmento_Mercado',
    'repeated_guest': 'Huesped_Repetido',
    'no_of_previous_cancellations': 'Cancelaciones_Previas',
    'no_of_previous_bookings_not_canceled': 'Reservas_Previas_NoCanceladas',
    'avg_price_per_room': 'Precio_Promedio_Habitacion',
    'no_of_special_requests': 'Solicitudes_Especiales',
    'booking_status': 'Estado_Reserva'
}

df.rename(columns=nombres_espanol, inplace=True)

In [ ]:
df.

,ID_Reserva,Num_Adultos,Num_Ninos,Noches_FinSemana,Noches_Semana,Tipo_Plan_Comidas,Estacionamiento_Requerido,Tipo_Habitacion,Dias_Antelacion,AÃ±o_Llegada,Mes_Llegada,Dia_Llegada,Tipo_Segmento_Mercado,Huesped_Repetido,Cancelaciones_Previas,Reservas_Previas_NoCanceladas,Precio_Promedio_Habitacion,Solicitudes_Especiales,Estado_Reserva
0,INN00001,2,0,1,2,Meal Plan 1,0,Room_Type 1,224,2017,10,2,Offline,0,0,0,65.00,0,Not_Canceled
1,INN00002,2,0,2,3,Not Selected,0,Room_Type 1,5,2018,11,6,Online,0,0,0,106.68,1,Not_Canceled
2,INN00003,1,0,2,1,Meal Plan 1,0,Room_Type 1,1,2018,2,28,Online,0,0,0,60.00,0,Canceled
3,INN00004,2,0,0,2,Meal Plan 1,0,Room_Type 1,211,2018,5,20,Online,0,0,0,100.00,0,Canceled
4,INN00005,2,0,1,1,Not Selected,0,Room_Type 1,48,2018,4,11,Online,0,0,0,94.50,0,Canceled
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36270,INN36271,3,0,2,6,Meal Plan 1,0,Room_Type 4,85,2018,8,3,Online,0,0,0,167.80,1,Not_Canceled
36271,INN36272,2,0,1,3,Meal Plan 1,0,Room_Type 1,228,2018,10,17,Online,0,0,0,90.95,2,Canceled
36272,INN36273,2,0,2,6,Meal Plan 1,0,Room_Type 1,148,2018,7,1,Online,0,0,0,98.39,2,Not_Canceled
36273,INN36274,2,0,0,3,Not Selected,0,Room_Type 1,63,2018,4,21,Online,0,0,0,94.50,0,Canceled
36274,INN36275,2,0,1,2,Meal Plan 1,0,Room_Type 1,207,2018,12,30,Offline,0,0,0,161.67,0,Not_Canceled

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36275 entries, 0 to 36274
Data columns (total 19 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   ID_Reserva                     36275 non-null  object
 1   Num_Adultos                    36275 non-null  int64
 2   Num_Ninos                      36275 non-null  int64
 3   Noches_FinSemana               36275 non-null  int64
 4   Noches_Semana                  36275 non-null  int64
 5   Tipo_Plan_Comidas              36275 non-null  object
 6   Estacionamiento_Requerido      36275 non-null  int64
 7   Tipo_Habitacion                36275 non-null  object
 8   Dias_Antelacion                36275 non-null  int64
 9   AÃ±o_Llegada                    36275 non-null  int64
 10  Mes_Llegada                    36275 non-null  int64
 11  Dia_Llegada                    36275 non-null  int64
 12  Tipo_Segmento_Mercado          36275 non-null  object
 13  Huesped_Repetido               36275 non-null  int64
 14  Cancelaciones_Previas          36275 non-null  int64
 15  Reservas_Previas_NoCanceladas  36275 non-null  int64
 16  Precio_Promedio_Habitacion     36275 non-null  float64
 17  Solicitudes_Especiales         36275 non-null  int64
 18  Estado_Reserva                 36275 non-null  object
dtypes: float64(1), int64(13), object(5)
memory usage: 5.3+ MB

In [8]:
for columna in df.columns:
    print(f"La columna {columna} tiene de datos:")
    print(df[columna].unique())
    print("")

La columna ID_Reserva tiene de datos:
['INN00001' 'INN00002' 'INN00003' ... 'INN36273' 'INN36274' 'INN36275']

La columna Num_Adultos tiene de datos:
[2 1 3 0 4]

La columna Num_Ninos tiene de datos:
[ 0  2  1  3 10  9]

La columna Noches_FinSemana tiene de datos:
[1 2 0 4 3 6 5 7]

La columna Noches_Semana tiene de datos:
[ 2  3  1  4  5  0 10  6 11  7 15  9 13  8 14 12 17 16]

La columna Tipo_Plan_Comidas tiene de datos:
['Meal Plan 1' 'Not Selected' 'Meal Plan 2' 'Meal Plan 3']

La columna Estacionamiento_Requerido tiene de datos:
[0 1]

La columna Tipo_Habitacion tiene de datos:
['Room_Type 1' 'Room_Type 4' 'Room_Type 2' 'Room_Type 6' 'Room_Type 5'
 'Room_Type 7' 'Room_Type 3']

La columna Dias_Antelacion tiene de datos:
[224   5   1 211  48 346  34  83 121  44   0  35  30  95  47 256  99  12
 122   2  37 130  60  56   3 107  72  23 289 247 186  64  96  41  55 146
  32  57   7 124 169   6  51  13 100 139 117  39  86  19 192 179  26  74
 143 177  18 267 155  46 128  20  40 196 188  17 110  68  73  92 171 134
 320 118 189  16  24   8  10 182 116 123 105 443 317 286 148  14  85  25
  28  80  11 162  82  27 245 266 112  88  69 273   4  97  31  62 197 280
 185 160 104  22 292 109 126 303  81  54  15 161 147  87 127 418 156  58
 433 111 195 119  59  78 335 103  70  76 144  49  77  36  79  21  33 164
 152  43 102  71 209  93  53 302 239  45 167 113  84   9 166 174  61 151
  52  67 282  38 175  89 133  65  66  50 159 386 115 237 125  91  29 221
 213 198  75 180 236 120 230  63 136 309 157 268 217  94 305  98  42 154
 330 137 184 232 304 114 257 265 191 101 259 149 170 271 207 108 210 222
 296 194 145 153 275 158 301 349 200 315 181 263 176 141 270 150 359 244
 219 142 138 276 178 163 377 290 216 226 258 254 193 131 208 215 190 381
 231 248 106 308 140 173 168 172  90 249 205 129 212 135 220 277 253 132
 183 255 223 336 288 229 319 199 203 228 246 235 294 281 202 361 287 291
 313 206 269 279 261 214 274 250 187 240 241 323 322 227 225 233 338 283
 327 204 352 165 251 299 314 285 238 328 278 332 243 201 307 272 252 242
 284 297 324 260 262 326 295 218 234 353 300 355 306 298 331 341 318 333
 372 311 310 345 264 325 293 348 350 351]

La columna AÃ±o_Llegada tiene de datos:
[2017 2018]

La columna Mes_Llegada tiene de datos:
[10 11  2  5  4  9 12  7  6  8  3  1]

La columna Dia_Llegada tiene de datos:
[ 2  6 28 20 11 13 15 26 18 30  5 10  4 25 22 21 19 17  7  9 27  1 29 16
  3 24 14 31 23  8 12]

La columna Tipo_Segmento_Mercado tiene de datos:
['Offline' 'Online' 'Corporate' 'Aviation' 'Complementary']

La columna Huesped_Repetido tiene de datos:
[0 1]

La columna Cancelaciones_Previas tiene de datos:
[ 0  3  1  2 11  4  5 13  6]

La columna Reservas_Previas_NoCanceladas tiene de datos:
[ 0  5  1  3  4 12 19  2 15 17  7 20 16 50 13  6 14 34 18  8 10 23 11 49
 47 53  9 33 22 24 52 21 48 28 39 25 31 38 26 51 42 37 35 56 44 27 32 55
 45 30 57 46 54 43 58 41 29 40 36]

La columna Precio_Promedio_Habitacion tiene de datos:
[ 65.   106.68  60.   ... 118.43 137.25 167.8 ]

La columna Solicitudes_Especiales tiene de datos:
[0 1 3 2 4 5]

La columna Estado_Reserva tiene de datos:
['Not_Canceled' 'Canceled']